# Generated by Django 5.2.3 on 2025-06-29 16:25

import coverde_ecommerce.models.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(default='Mensagem via formulário de contacto', max_length=200)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Mensagem de Contacto',
                'verbose_name_plural': 'Mensagens de Contacto',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe uma conta com este email.'}, max_length=254, unique=True, verbose_name='email address')),
                ('tipo', models.CharField(choices=[('C', 'Consumidor'), ('P', 'Produtor'), ('A', 'Administrador')], default='C', max_length=1, verbose_name='Tipo de Utilizador')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Use +351 123456789', regex='^\\+?[\\d\\s]{9,15}$')], verbose_name='Telefone')),
                ('nif', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NIF deve conter exatamente 9 dígitos', regex='^[0-9]{9}$')], verbose_name='NIF')),
                ('morada', models.TextField(blank=True, null=True, verbose_name='Morada')),
                ('codigo_postal', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use 1234-567', regex='^\\d{4}-\\d{3}$')], verbose_name='Código Postal')),
                ('localidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidade')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to=coverde_ecommerce.models.models.user_directory_path, verbose_name='Imagem de Perfil')),
                ('data_registo', models.DateTimeField(auto_now_add=True, db_column='data_registo', verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'db_table': 'ecommerce_coverde_utilizadores',
                'ordering': ['-data_registo'],
            },
            managers=[
                ('objects', coverde_ecommerce.models.models.UtilizadorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria (mínimo 3 caracteres)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='O nome deve conter apenas letras, números, espaços ou hífens', regex='^[\\w\\s-]+$')], verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs', max_length=60, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da categoria', verbose_name='Descrição')),
                ('icone', models.CharField(default='fa-leaf', help_text='Classe do ícone (ex: Font Awesome)', max_length=30, verbose_name='Ícone')),
                ('ordem_menu', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição no menu', verbose_name='Ordem no Menu')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'ecommerce_coverde_categoria',
                'ordering': ['ordem_menu', 'nome'],
                'indexes': [models.Index(fields=['slug'], name='categoria_slug_idx'), models.Index(fields=['ordem_menu'], name='categoria_ordem_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código do Pedido')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Estado do Pedido')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (€)')),
                ('endereco_entrega', models.TextField(verbose_name='Endereço de Entrega')),
                ('metodo_pagamento', models.CharField(max_length=50, verbose_name='Método de Pagamento')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL Amigável')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço Unitário (€)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('unidade', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('un', 'Unidade'), ('l', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('fd', 'Fardo')], default='un', max_length=2, verbose_name='Unidade de Venda')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Stock')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=coverde_ecommerce.models.models.product_image_upload_path, verbose_name='Imagem Principal')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Venda')),
                ('destaque', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('data_colheita', models.DateField(blank=True, help_text='Data aproximada de colheita ou produção', null=True, verbose_name='Data de Colheita/Produção')),
                ('certificado_biologico', models.BooleanField(default=False, help_text='Marque se o produto possui certificação orgânica/biológica', verbose_name='Certificação Biológica')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='coverde_ecommerce.categoria', verbose_name='Categoria Principal')),
                ('produtor', models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Produtor/Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-destaque', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='coverde_ecommerce.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coverde_ecommerce.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='coverde_ecommerce.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverde_ecommerce.produto')),
            ],
            options={
                'verbose_name': 'Item do Carrinho',
                'verbose_name_plural': 'Itens do Carrinho',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='coverde_ecommerce.produto')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'ecommerce_coverde_favorito',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='utilizador',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='utilizador',
            index=models.Index(fields=['tipo'], name='tipo_utilizador_idx'),
        ),
        migrations.AddIndex(
            model_name='utilizador',
            index=models.Index(fields=['nif'], name='nif_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['slug'], name='coverde_eco_slug_c5318a_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['disponivel', 'destaque'], name='coverde_eco_disponi_ac11c4_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'disponivel'], name='coverde_eco_categor_13511d_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['preco'], name='coverde_eco_preco_37da25_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_produto_slug'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0.01)), name='preco_positivo'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('utilizador', 'produto')},
        ),
    ]
