# Generated by Django 5.2.3 on 2025-06-30 11:08

import coverde_ecommerce.models.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverde_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem_menu', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='favorito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-destaque', '-data_criacao']},
        ),
        migrations.RemoveConstraint(
            model_name='produto',
            name='unique_produto_slug',
        ),
        migrations.RemoveConstraint(
            model_name='produto',
            name='preco_positivo',
        ),
        migrations.RemoveIndex(
            model_name='categoria',
            name='categoria_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='categoria',
            name='categoria_ordem_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='coverde_eco_slug_c5318a_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='coverde_eco_disponi_ac11c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='coverde_eco_categor_13511d_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='coverde_eco_preco_37da25_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilizador',
            name='email_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilizador',
            name='tipo_utilizador_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilizador',
            name='nif_idx',
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(default='fa-leaf', max_length=30),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ordem_menu',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coverde_ecommerce.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='certificado_biologico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_colheita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=coverde_ecommerce.models.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produtor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('un', 'Unidade'), ('l', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('fd', 'Fardo')], default='un', max_length=2),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}$', 'Formato inválido. Use 1234-567')], verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='data_registo',
            field=models.DateTimeField(auto_now_add=True, db_column='data_registo', verbose_name='Data de Registo'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', 'NIF deve conter exatamente 9 dígitos')], verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s]{9,15}$', 'Formato de telefone inválido. Use +351 123456789')], verbose_name='Telefone'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
        migrations.AlterModelTable(
            name='favorito',
            table=None,
        ),
    ]
