# Generated by Django 5.2.3 on 2025-06-30 11:43

import coverde_ecommerce.models.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverde_ecommerce', '0002_alter_carrinho_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Mensagem de Contacto', 'verbose_name_plural': 'Mensagens de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}$', 'Formato inválido. Use 1234-567')]),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='data_registo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=coverde_ecommerce.models.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='morada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'NIF deve conter exatamente 9 dígitos')]),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s]{9,15}$', 'Formato de telefone inválido. Use +351 123456789')]),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='tipo',
            field=models.CharField(choices=[('C', 'Consumidor'), ('P', 'Produtor'), ('A', 'Administrador')], default='C', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('utilizador', 'produto'), name='unique_favorito'),
        ),
    ]
