# Generated by Django 5.2.2 on 2025-06-09 21:35

import django.core.validators
import django.db.models.deletion
import ecommerce_coverde.models.produto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_coverde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='ecommerce_coverde.categoria', verbose_name='Categoria Principal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='certificado_biologico',
            field=models.BooleanField(default=False, help_text='Produto possui certificação orgânica/biológica?', verbose_name='Certificação Biológica'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_colheita',
            field=models.DateField(blank=True, help_text='Data aproximada de produção do item', null=True, verbose_name='Data de Colheita/Produção'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Informações técnicas e características do produto', verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibir em seções especiais do site', verbose_name='Produto em Destaque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Exibir este produto no catálogo?', verbose_name='Disponível para Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de destaque do produto (ratio recomendado 1:1)', null=True, upload_to=ecommerce_coverde.models.produto.product_image_upload_path, verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Nome completo do produto para exibição', max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço Unitário (€)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produtor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Produtor/Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente a partir do nome', max_length=120, unique=True, verbose_name='URL Amigável'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade disponível para venda imediata', verbose_name='Quantidade em Stock'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('un', 'Unidade'), ('l', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('fd', 'Fardo')], default='un', max_length=2, verbose_name='Unidade de Venda'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['preco'], name='ecommerce_c_preco_7e3cc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0.01)), name='preco_positivo'),
        ),
        migrations.AlterModelTable(
            name='produto',
            table=None,
        ),
    ]
