# Generated by Django 5.2.2 on 2025-06-10 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_coverde', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemencomenda',
            name='encomenda',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='encomenda',
        ),
        migrations.RemoveField(
            model_name='itemencomenda',
            name='produto',
        ),
        migrations.AlterModelOptions(
            name='carrinho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens do Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='sessao_key',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='consumidor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código do Pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.TextField(default='Desconhecido', verbose_name='Endereço de Entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='utilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='utilizador',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ecommerce_coverde.carrinho'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_coverde.produto'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(default='Indefinido', max_length=50, verbose_name='Método de Pagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Estado do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (€)'),
        ),
        migrations.AlterModelTable(
            name='carrinho',
            table=None,
        ),
        migrations.AlterModelTable(
            name='itemcarrinho',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ecommerce_coverde.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce_coverde.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Encomenda',
        ),
        migrations.DeleteModel(
            name='ItemEncomenda',
        ),
    ]
